### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by wgsthink** [rafmudaf/openfast#12]
All the pictures in this documentation are not shown.  Besides, How to run a simulation in Matlab?  There is a link of documentation in 2014, http://wind.nrel.gov/designcodes/simulators/fast/,  but it's invalid. 
So, how to run in the new edition FAST in Matlab?  Thank you!

**Comment by jjonkman** [comment]
Dear @wgsthink,

Until all of the prior FAST v8 documentation is ported into OpenFAST, you can find guidance for running the MATLAB/Simulink-FAST interface in the old FAST v7 User's Guide and old FAST v8 ReadMe file.  As I announced on our forum here: https://wind.nrel.gov/forum/wind/viewtopic.php?f=38&t=1001, the NWTC Information Portal has been taken down and we are working to establish a replacement website, hopefully soon. I've now shared the old FAST v7 User's Guide here: https://drive.google.com/file/d/1d_-vRRK3sXlunf1I1tDmtSWUveed91gg/view?usp=sharing and the FAST v8 ReadMe file here: https://drive.google.com/file/d/17LDwMnCVmLfbRWSaVFxxqphVrtawMwlj/view?usp=sharing.

Best regards,

**Comment by wgsthink** [comment]
@jjonkman  Thank you very much!   I think that the Google Drive link can put into the OpenFAST documentation. Before I ask you the information about the FAST, I also searched for some information on our forum. Unfortunately,  after failing to visit some links, I gave up. Finally, thank you and your team.
