### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by coenjan** [rafmudaf/openfast#25]
**Bug description**
Dear, It seems that the figures are not included in the file. For example, in section 4.3.3.1. "Definition of the FAST v8 Interface to Simulink" you refer to figure 8, but figure 8 is not included (although the caption of figure 8 does exist). Could I find the figures somewhere else? Kind regards, Coen

**Comment by rafmudaf** [comment]
Thanks @coenjan If you are looking at the documentation at http://raf-openfast.readthedocs.io this will most certainly be out of date. Notice the `raf-` in the URL. The official OpenFAST documentation is linked from the main repository at https://github.com/openfast/openfast and the URL is http://openfast.readthedocs.io.
